### ISSUE TITLE
modem_console get_module_name does not call the SHINY function (IDFGH-11628)

### ISSUE THREAD

**Issue by dajtxx** [espressif/esp-protocols#452]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

While trying to implement a custom module by experimenting with the modem_console example I found the SHINY module is not called when using the get_module_name command:

```
I (539) main_task: Started on CPU0
I (549) main_task: Calling app_main()
I (569) uart: queue free spaces: 30
I (569) modem_console: Initializing esp_modem for the SHINY module...

Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.
esp> get_module_name
I (19569) modem_console: Reading module name...
E (24569) modem_console: Failed with TIMEOUT
Command returned non-zero error code: 0x1 (ERROR)
```

The logging output shows the custom SHINY module is being used, but instead of returning the hard-coded module name from the overridden method it is calling the generic module method which issues an AT command.

**Comment by david-cermak** [comment]
Okay, it seems that this command is overwritten in

https://github.com/espressif/esp-protocols/blob/82c2cf8936d4d363617825c3ed4028d1b0d20386/components/esp_modem/examples/modem_console/main/my_module_dce.cpp#L45-L46

I'm sorry, I wanted to demonstrate how to handle URC messages in 7547267336d7e2e7dc2002d8cb8f14a84a68c541 and forgot that this would basically replace that overridden command.
To use that command again, we need to create the `dce` using standard `esp_modem::DCE` rather than `Shiny::DCE` by:
```patch
diff --git a/components/esp_modem/examples/modem_console/main/modem_console_main.cpp b/components/esp_modem/examples/modem_console/main/modem_console_main.cpp
index b703d99..ba8f791 100644
--- a/components/esp_modem/examples/modem_console/main/modem_console_main.cpp
+++ b/components/esp_modem/examples/modem_console/main/modem_console_main.cpp
@@ -132,7 +132,8 @@ extern "C" void app_main(void)
 
 #if defined(CONFIG_EXAMPLE_MODEM_DEVICE_SHINY)
     ESP_LOGI(TAG, "Initializing esp_modem for the SHINY module...");
-    auto dce = create_shiny_dce(&dce_config, uart_dte, esp_netif);
+    auto dce = esp_modem::dce_factory::Factory::build_unique<MyShinyModem>(&dce_config, uart_dte, esp_netif);
 #elif defined(CONFIG_EXAMPLE_MODEM_DEVICE_BG96)
     ESP_LOGI(TAG, "Initializing esp_modem for the BG96 module...");
     auto dce = create_BG96_dce(&dce_config, uart_dte, esp_netif);
```
I'll fix the example and add more comments!

If you just want to modify few commands, you can check the pppos_client example (this is much simpler):

https://github.com/espressif/esp-protocols/blob/82c2cf8936d4d363617825c3ed4028d1b0d20386/components/esp_modem/examples/pppos_client/main/custom_module.hpp#L11-L42

(unlike the `Shiny::DCE` class which completely rewrites the defaults and even uses custom commands for handling URC)
