### ISSUE TITLE
Feature request: add support for LTE-M PSM & eDRX modes to save energy (IDFGH-7548)

### ISSUE THREAD

**Issue by bbinet** [espressif/esp-protocols#54]
It would be great if esp-modem would support LTE-M PSM and eDRX features, so that we could build low-power but connected devices for IoT.

Do you plan to implement such features in the (near) future?

**Comment by bbinet** [comment]
During PSM sleep duration of the modem, we want our ESP to deep sleep as well to save energy, so the tricky part might be when we wakeup from deep sleep, to recover to the same state we were before sleeping (e.g. same command/data/cmux mode).

It would be great to have an example which demonstrates how to use the PSM feature in projects with energy constraints.

**Comment by david-cermak** [comment]
Any preference towards the device and ESP chip? (If not we'd probably choose ESP32 and SIM7000 series)

**Comment by bbinet** [comment]
Thank you for your reply @david-cermak.
Yes this request is still valid: for now, I'm switching the modem off before my esp enters deep sleep, but then the modem needs to register again at wakeup so there is room for improvements to save energy by using PSM mode.
On my side, I'm using esp32c3, and modem BG95-M3 (same AT commands as BG96), so if possible, it would be great to have an example working with this device.
Thanks a lot!

**Comment by nilesh-dryad** [comment]
@david-cermak PSM and eDRX are 3GPP standard. Any device supporting those feature would be fine. I have spent lots of time making LTE modem works in low power mode. Couldn't get the success. At the end I somehow managed to get it working at cost of losing few bytes at the starts. 

The problem is not when you want to send data to Internet through modem. Actual problem is when you want to receive data from modem and ESP is in light sleep. PPP will stop working as soon as you enter in light sleep. There is nothing you can do in esp to keep it working. It's a modem who drops the connection. You will have to implement AT command based network interface. Here also as I said, you will loose few bytes. for e.g. if you are connected TCP/UDP socket using AT command and if you receive data from Internet, modem will send SRING, 0, 17, <data>. Based on the baud rate setting of 19200, in my case I was always loosing SRING Insterad I was getting comma byte and I was able to parse it after some checking and I iterate through all the AT response I needed in my application. I was able to parse each response. That's why I implemented it it worked for me. But this is not a generic solution.

**Comment by bbinet** [comment]
Thank you @david-cermak for this LTE-M PSM example.
I will test it with the bg95-m3 modem as soon as I have some time.

**Comment by bbinet** [comment]
And thank you @espressif-abhikroy for the implementation
